name: CI / CD

on:
  push:
    branches:
      - main
    paths:
      './signupfront'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
    
      - name: Build and push an image to container registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a4u1j4l3
          docker build -t signup .
          docker tag signup:latest public.ecr.aws/a4u1j4l3/signup:latest
          docker push public.ecr.aws/a4u1j4l3/signup:latest  
        working-directory: ./signupfront
  
      - uses: bitovi/github-actions-deploy-eks-helm@v1.2.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          cluster-name: skyu-eks-cluster
          config-files: signupfront/signuphelm/values.yaml
          chart-path: signupfront/signuphelm
          name: signhelm