name: CI Pipeline

on:
  schedule:
      - cron: '06 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: |
          echo "Hello World"