name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: terraform initiate
        run: terraform init

      - name: terraform apply
        run: terraform apply --auto-approve

      - run: aws eks update-kubeconfig --name skyu-eks-cluster --region ${{ secrets.AWS_REGION }}

      - run: kubectl get pods -A

      - run: kubectl get all -n argocd

      - run: aws secretsmanager get-secret-value --secret-id argocd --region ${{ secrets.AWS_REGION }}

      - name: Tekton Pipeline Installation
        run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

     

      - name: Tekton Trigger Installation
        run:  |
            kubectl apply --filename \
            https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
            kubectl apply --filename \
            https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
            
      - name: Tekton Dashboard Installation
        run: kubectl apply --filename https://storage.googleapis.com/tekton-releases/dashboard/latest/release.yaml

      - run: kubectl proxy
      
