name: CI Pipeline

on:
  schedule:
      - cron: '02 11 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: |
          echo "Hello World"