name: CI Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: |
          echo "Hello World"