name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'devops/**'
    schedule:
      - cron: '57 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: |
          echo "Hello World"