name: CI Pipeline

on:
  schedule:
    - cron: '2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: |
          echo "Hello World"