name: Deploy SkyU.IO to Cloudfront

on: workflow_dispatch
jobs:
  STAGING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./test
  RELEASE:
    runs-on: ubuntu-latest
    needs: [STAGING]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R