name: Deploy SkyU.IO to Cloudfront

on: 
  push:
    branches:
      - main
jobs:
  STAGING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./test
  RELEASE:
    runs-on: ubuntu-latest
    needs: [STAGING]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with: 
        filename: release.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: alpha
        release_name: alpha0.0.1