name: tfsec
on:
  push:
    branches:
      - c
   
jobs:
  tfsecr:
    name: tfsec sarif report path 2
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'Path1/**'

      # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        run: echo v.${{ github.sha }}

  tfsecrt:
    name: tfsec sarif report path 2
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'Path2/**'

        # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        run: echo v.${{ github.sha }}