name: tfsec
on:
  push:
    branches:
      - c
    paths:
      - 'Path1/**'
      - 'Path2/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      Path1: ${{ steps.changes.outputs.Path1 }}
      Path2: ${{ steps.changes.outputs.Path2 }}
    steps:
    - uses: actions/checkout@v3
      name: Checkout project to determine changed files
      with:
        fetch-depth: 2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        base: c
        filters: |
          Path1:
            - 'Path1/**'
          Path2:
            - 'Path2/**'          

  Path1:
    needs: changes
    if: ${{ needs.changes.outputs.Path1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo v.${{ github.sha }}

  Path2:
    needs: changes
    if: ${{ needs.changes.outputs.Path2 == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo v.${{ github.sha }}

  Hello:
    needs: [Path1,Path2]
    if: ${{ needs.changes.outputs.Path2 == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo v.${{ github.sha }}