name: tfsec
on:
  push:
    branches:
      - c
   
jobs:
    
  tfsecr:
    name: tfsec sarif report path 2
    runs-on: ubuntu-latest
    steps:
      - run: echo v.${{ github.sha }}

      - uses: sanu1020/eks-cluster/.github/workflows/reusuable-workflow.yml@c