name: Deploy SkyU.IO to Cloudfront

on: 
  push:
    branches:
      - main

jobs:
  STAGING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./test
  RELEASE:
    runs-on: ubuntu-latest
     permissions:
      contents: write
    needs: [STAGING]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with: 
        filename: release.zip

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag_name: "alpha"
        release_name: "alpha0.0.1"