name: Deploy SkyU.IO to Cloudfront

on: 
  branches:
    - main
jobs:
  STAGING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./test
  RELEASE:
    runs-on: ubuntu-latest
    needs: [STAGING]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with: 
        filename: 'release.zip'