name: Deploy SkyU.IO to Cloudfront

on: workflow_dispatch
jobs:
  STAGING:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./test