name: tfsec

on:
  pull_request_target:
    branches:
      - dev

jobs:
  tfsec:
    if: github.event.pull_request.merged == true
    name: tfsec sarif report path 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Echo version and SHA for Path1
        run: echo "v.${{ github.sha }}"

  tfsecr:
    name: tfsec sarif report path 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Echo version and SHA for Path2
        run: echo "v.${{ github.sha }}"
