name: tfsec
on:
  push:
    branches:
      - c
   
jobs:
  tfsecr:
    name: tfsec sarif report path 2
    runs-on: ubuntu-latest
    steps:
      - run: echo v.${{ github.sha }}
  
  gitHub-actions-demo:
    needs: [tfsecr]
    uses: ./.github/workflows/reusuable-workflow.yml