name: tfsec
on:
  push:
    branches:
      - main
    paths: 
      - 'Path1/**'
      - 'Path2/**'
jobs:
  tfsec:
    if: github.event.path == 'Path1/**'
    name: tfsec sarif report path 1
    runs-on: ubuntu-latest
    steps:
      - run: echo v.${{ github.sha }
  
  tfsecr:
    if: github.event.path == 'Path2/**'
    name: tfsec sarif report path 2
    runs-on: ubuntu-latest
    steps:
      - run: echo v.${{ github.sha }}